### PR TITLE
Add str()

### PR DESCRIPTION
**Pull request by wrathematics**
`NA`'s are still a little funny for `bool`'s (not sure how to fix this without changing it to int...) and in strings, which I have no idea how to handle; `NA_STRING` doesn't want to play nice, and I haven't looked up its internal representation to figure out what it is yet.

Anyway, here's some examples:
```r
library(triebeard)
trie <- create_trie(keys = c("AO", "AEO", "AAI", "AFT", "QZ", "RF"),
                    values = c("Audobon", "alasjkdflkasjdflkasjdflkjasldkfjalskdjflaksjdflkasjdlfkjasldkfj", "Ann Arbor", "Austin", "Queensland", "Raleigh"))
 
str(trie)
## string_trie
##   Keys:   chr [1:6] "AAI" "AEO" "AFT" "AO" "QZ" "RF" 
##   Values: str [1:6] "Ann Arbor"  ...
 
trie <- create_trie(keys = c("AO", "AEO", "AAI", "AFT", "QZ", "RF"),
 values = c("Audobon", "Atlanta", "Ann Arbor", "Austin", "Queensland", "Raleigh"))
 
str(trie)
## string_trie
##   Keys:   chr [1:6] "AAI" "AEO" "AFT" "AO" "QZ" "RF" 
##   Values: str [1:6] "Ann Arbor"  "Atlanta"  "Austin"  "Audobon"  "Queensland"  ...
 
 
trie <- create_trie(keys=letters[1:4], values=c(TRUE, TRUE, FALSE, NA))
str(trie)
## logical_trie
##   Keys:   chr [1:4] "a" "b" "c" "d" 
##   Values: logi [1:4] TRUE TRUE FALSE TRUE 
 
trie <- create_trie(keys=letters[1:4], values=c(pi, NA, NA, -pi))
str(trie)
## numeric_trie
##   Keys:   chr [1:4] "a" "b" "c" "d" 
##   Values: num [1:4] 3.14159 NA NA -3.14159 
 
trie <- create_trie(keys=letters[1:4], values=c(1L, NA_integer_, 2L, NA_integer_))
str(trie)
## integer_trie
##   Keys:   chr [1:4] "a" "b" "c" "d" 
##   Values: int [1:4] 1 NA 2 NA 
 
trie <- create_trie(keys=letters[1:4], values=c("x", "y", NA_character_, "z"))
str(trie)
## string_trie
##   Keys:   chr [1:4] "a" "b" "c" "d" 
##   Values: str [1:4] "x"  "y"  "NA"  "z"  
```

### CODE REVIEW

**Comment by Ironholds** [comment]
Yeah, NAs simply shouldn't be working at all; C++-side, only Rcpp types (CharacterVector, NumericVector) have them; C++ types (std::vector < std::string >) do not.

(The logical fuckery is probably because things get Really Strange around what logicals consider an NA and sometimes an NA_REAL is the answer and ??? I don't understand it but I'm assured it's a known thing and a regrettedly unfortunate one)

This feels kind of a complex solution, I guess. My initial thoughts were to just replace "f" in the current code with na.omit(get_keys(trie)[1:6]) and the same for values, which would provide something equivalent-looking without more (bulky) compiled code - str() isn't a space where we particularly care for speed.

**Comment by Ironholds** [comment]
Also are you secretly a C++ fan or is nothing going on in TN right now? :P

**Comment by wrathematics** [comment]
I think what's happening with the logicals is that R really only tracks something as "logical" for printing purposes, but really, internally it's an int. But in C++, `bool` is a `bool`, so it casts the int representation to a `bool`. Everything but 0, including `NA_INTEGER == INT_MIN` becomes a 1.

It is definitely complex, but mimics the way `str()` works for lists. The reason I wanted to avoid those things like `get_keys()` is the trie could conceivably be large, and didn't want to waste the time making copies and constructing the vectors just for a quick inspection of the object. imo `str()` should run near instantaneously.

And no, I don't like C++ ;)

**Comment by Ironholds** [comment]
Makes sense!

**Pull request merged**
